### ISSUE TITLE
Error: File not found with singular glob: /var/www/magento/js/prototype/prototype.js

### ISSUE THREAD

**Issue by xekon** [xekon/mbootstrap#1]
Updated the ReadMe. Made progress installing this but when i get toward the end where yo run **gulp** I have encountered an error, I believe its looking for a file that magento had once upon a time, it appears to be a file that Magento 2.4.1 does not have:

**/var/www/magento/js/prototype/prototype.js**

```
cd /var/www/magento
gulp

[10:23:36] Using gulpfile /var/www/magento/gulpfile.js
[10:23:36] Starting 'default'...
[10:23:36] Starting 'build'...
[10:23:36] Starting 'build-mbootstrap'...
[10:23:36] Starting 'build-base'...
[10:23:36] Starting 'build-base-scripts'...
[10:23:36] Finished 'build-base-scripts' after 116 ms
[10:23:36] Finished 'build-base' after 116 ms
[10:23:36] Starting 'build-mbootstrap-scripts'...
[10:23:36] Finished 'build-mbootstrap-scripts' after 20 ms
[10:23:36] Starting 'build-mbootstrap-styles-clean'...
[10:23:36] Finished 'build-mbootstrap-styles-clean' after 5.49 ms
[10:23:36] Starting 'build-mbootstrap-styles'...
[10:23:36] The following tasks did not complete: default, build, build-mbootstrap, build-mbootstrap-styles
[10:23:36] Did you forget to signal async completion?
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /var/www/magento/js/prototype/prototype.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/var/www/node_modules/gulp/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:286:20)
    at Glob.emit (events.js:198:13)
    at Glob.EventEmitter.emit (domain.js:448:20)
    at Glob._finish (/var/www/node_modules/gulp/node_modules/glob/glob.js:197:8)
    at done (/var/www/node_modules/gulp/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/var/www/node_modules/gulp/node_modules/glob/glob.js:688:12)
    at /var/www/node_modules/gulp/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/var/www/node_modules/gulp/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/var/www/node_modules/gulp/node_modules/glob/glob.js:764:12)
Emitted 'error' event at:
    at DestroyableTransform.EventEmitter.emit (domain.js:461:12)
    at Pumpify.emit (events.js:198:13)
    at Pumpify.EventEmitter.emit (domain.js:448:20)
    at Pumpify.Duplexify._destroy (/var/www/node_modules/gulp/node_modules/duplexify/index.js:191:15)
    at /var/www/node_modules/gulp/node_modules/duplexify/index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by xekon** [comment]
It seems the file is actually located at: **/var/www/magento/lib/web/prototype/prototype.js**

Now I just need to figure out the reason that gulp is looking for it in the other location.

**Comment by xekon** [comment]
This is only a problem because this theme is for magento 1.9.x and I was trying to use it with 2.4.x
